-- country_picks 테이블에 popularity 컬럼 추가 및 중국 데이터 삽입

alter table country_picks add column if not exists popularity text;

insert into country_picks (country_code, flag, country_ko, country_en, country_zh, country_ja, rank_num, name_ko, name_en, name_zh, name_ja, score, popularity, reason_ko, reason_en, reason_zh, reason_ja, source_ko, source_en, source_zh, source_ja, source_url) values
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 1, '농심 신라면', 'Nongshim Shin Ramyun', '农心辛拉面', '農心辛ラーメン', null, '🔥🔥🔥', '중국에서 인지도가 가장 높은 한국 라면. 진한 매운 국물과 쫄깃한 면발, 한국 드라마식 계란·김치 조리법으로 유명.', 'The most recognized Korean ramen in China. Known for its bold spicy broth and chewy noodles — often cooked K-drama style with egg and kimchi.', '在中国知名度最高的韩国拉面。以浓郁辣汤和劲道面条著称，常按韩剧做法加鸡蛋和泡菜。', '中国での知名度No.1韓国ラーメン。濃い辛いスープともちもち麺、韓国ドラマ風の卵・キムチ調理法で有名。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 2, '오뚜기 진라면', 'Ottogi Jin Ramen', '不倒翁真拉面', 'オットギ ジンラーメン', null, '🔥🔥🔥', '순한맛·매운맛 두 버전 모두 꾸준한 인기. 순한맛의 은은한 해물 국물을 선호하는 이들도 많음.', 'Both mild and spicy versions are consistently popular. Many prefer the mild version for its subtle seafood broth.', '温和版和辣味版都持续受欢迎，不少人偏爱温和版淡雅的海鲜汤底。', 'マイルドと辛口の両バージョンが安定した人気。マイルドの上品な海鮮スープを好む人も多い。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 3, '농심 안성탕면', 'Nongshim Ansungtangmyun', '农心安城汤面', '農心アンソンタン麺', null, '🔥🔥🔥', '은은하게 매운 사골 국물. 강한 맵기를 부담스러워하는 사람에게 인기.', 'Mildly spicy beef bone broth. Popular with those who find intense spice overwhelming.', '微辣牛骨汤底，受不了强烈辣味的人很喜欢。', 'ほんのり辛い牛骨スープ。強い辛さが苦手な人に人気。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 4, '농심 짜파게티', 'Nongshim Chapagetti', '农心炸酱意面', '農心チャパゲティ', null, '🔥🔥', '영화 〈기생충〉 노출로 화제. 윤기 나는 짜장 소스와 두꺼운 면이 특징.', 'Went viral after appearing in the film Parasite. Known for its glossy black bean sauce and thick noodles.', '因电影《寄生虫》走红。以光亮的炸酱和粗面条为特色。', '映画『パラサイト』で話題に。つやつやのジャージャーソースと太麺が特徴。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 5, '농심 너구리', 'Nongshim Neoguri', '农心貉子拉面', '農心たぬきラーメン', null, '🔥🔥', '굵은 면발의 쫄깃한 식감. 짜파게티와 섞은 ''짜파구리''로도 유명.', 'Chewy thick noodles. Also famous as ''Chapaguri'' when mixed with Chapagetti.', '粗面条嚼劲十足，与炸酱意面混合的"炸酱乌冬"也很有名。', 'もちもちの太麺。チャパゲティと混ぜた「チャパグリ」としても有名。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 6, '팔도 비빔면', 'Paldo Bibim Myeon', '八道拌面', 'パルド ビビン麺', null, '🔥🔥', '매콤달콤한 비빔소스. 삶은 계란·오이·고수 토핑과 잘 어울림.', 'Sweet and spicy bibim sauce. Pairs great with boiled egg, cucumber, and cilantro.', '酸甜辣拌面酱，搭配水煮蛋、黄瓜、香菜食用更佳。', '甘辛いビビムソース。ゆで卵・きゅうり・パクチーとの相性が抜群。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 7, '농심 육개장 사발면', 'Nongshim Yukgaejang Bowl', '农心肉汤碗面', '農心ユッケジャン サバル麺', null, '🔥🔥', '가성비 좋은 소고기맛 국물. 짭짤하고 살짝 매운 맛.', 'Great value beef broth. Salty with a mild kick of spice.', '性价比高的牛肉汤底，咸香微辣。', 'コスパの良い牛肉スープ。塩辛くほんのり辛い味。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 8, '팔도 왕뚜껑', 'Paldo Wang Ttukkeong', '八道王盖碗面', 'パルド ワントゥッコン', null, '🔥', '큰 용기, 부드럽게 잘 퍼지는 면발이 특징.', 'Large cup size with noodles that cook to a pleasantly soft texture.', '大碗装，面条煮后口感软滑。', '大きめカップで、柔らかくほぐれる麺が特徴。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综합出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 9, '삼양 불닭볶음면', 'Samyang Buldak Bokkeum Myeon', '三养火鸡炒面', 'サムヤン ブルダック炒め麺', null, '🔥🔥🔥', '초강력 매운맛의 대표주자. 삼양이 한국 라면 수출 1위 브랜드(전체 수출량 약 50%)를 차지하는 데 큰 역할. SNS 챌린지로 확산.', 'The icon of extreme spice. Played a huge role in making Samyang the #1 Korean ramen export brand (~50% of total exports). Spread via SNS challenges.', '超级辣味代表，助力三养成为韩国拉面出口第一品牌（约占总出口量50%），通过SNS挑战广泛传播。', '激辛の代名詞。三養を韓国ラーメン輸出No.1ブランド（全体の約50%）にした立役者。SNSチャレンジで拡散。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null),
('cn', '🇨🇳', '중국', 'China', '中国', '中国', 10, '오뚜기 참깨라면', 'Ottogi Chamgae Ramyun', '不倒翁芝麻拉面', 'オットギ ごまラーメン', null, '🔥', '고소한 참깨 향과 매콤한 국물의 조화.', 'A harmonious blend of nutty sesame aroma and spicy broth.', '香浓芝麻香与辣汤的完美融合。', '香ばしいごまの香りと辛いスープの調和。', '수출량·리뷰·판매 데이터 종합', 'Based on export volume, reviews & sales data', '综合出口量·评价·销售数据', '輸出量·レビュー·販売データ総合', null);
