-- 베트남 인기 한국 라면 Top 8 데이터 삽입 (Bún Đậu Mắm Tôm Tiến Hải 에디터 선정)

insert into country_picks (country_code, flag, country_ko, country_en, country_zh, country_ja, rank_num, name_ko, name_en, name_zh, name_ja, score, popularity, reason_ko, reason_en, reason_zh, reason_ja, source_ko, source_en, source_zh, source_ja, source_url) values
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 1, '삼양 까르보 불닭볶음면', 'Samyang Carbonara Buldak', '三养卡波那拉火鸡炒面', 'サムヤン カルボナーラ ブルダック', null, null, '캐러멜 소스로 매운맛과 단맛의 균형을 맞춘 전 세계적 열풍 제품. 굵고 쫄깃한 면발이 특징.', 'A global phenomenon balancing heat and sweetness with a caramel sauce. Known for its thick, chewy noodles.', '以焦糖酱平衡辣味与甜味，风靡全球。以粗实弹牙的面条为特色。', 'キャラメルソースで辛さと甘さのバランスを取った世界的ヒット商品。太くもちもちした麺が特徴。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 2, '농심 짜파게티', 'Nongshim Chapagetti', '农心炸酱意面', '農心チャパゲティ', null, null, '맵지 않은 정통 짜장 소스. 구수하고 은은한 단맛으로 남녀노소 부담 없이 즐길 수 있음.', 'Authentic black bean sauce with no spice. Rich and mildly sweet — enjoyed by all ages.', '不辣的正宗炸酱，浓郁带淡淡甜味，老少皆宜。', '辛くない本格ジャージャーソース。コクがあり甘みほんのり、老若男女問わず楽しめる。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 3, '농심 김치라면', 'Nongshim Kimchi Ramyun', '农心泡菜拉面', '農心キムチラーメン', null, null, '새콤달콤한 김치 맛에 순하게 매콤함. 느끼함을 잡아주는 용도로도 소개됨.', 'Sweet and tangy kimchi flavor with a mild kick. Also recommended as a palate cleanser for greasy foods.', '酸甜泡菜味，微微辣，也被推荐用来解腻。', '甘酸っぱいキムチ味にほんのり辛さ。脂っこさを和らげる用途でも紹介。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 4, '삼양 라볶이면', 'Samyang Rabokki Ramen', '三养炒年糕拉面', 'サムヤン ラポッキ麺', null, null, '라면+떡볶이 조합. 쫄깃한 면발과 부드러운 떡, 매콤하고 진한 소스가 특징.', 'Ramen meets tteokbokki. Chewy noodles, soft rice cakes, and a thick spicy sauce.', '拉面与炒年糕的组合，劲道面条、软糯年糕搭配浓郁辣酱。', 'ラーメン×トッポッキの組み合わせ。もちもち麺と柔らかい餅、濃い辛いソースが特徴。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 5, '오뚜기 똠얌 수프면', 'Ottogi Tom Yum Soup Ramen', '不倒翁冬阴功汤面', 'オットギ トムヤムスープ麺', null, null, '한국 제품이지만 태국식 똠얌 맛. 새콤매콤하고 시원한 국물이 특징.', 'A Korean ramen with Thai tom yum flavor. Tangy, spicy, and refreshing broth.', '韩国产品但有泰式冬阴功风味，酸辣清爽的汤底为特色。', '韓国製品ながらタイ風トムヤム味。酸っぱくて辛くてすっきりしたスープが特徴。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 6, '삼양 불닭 커리', 'Samyang Buldak Curry', '三养火鸡咖喱炒面', 'サムヤン ブルダック カレー', null, null, '카레 향이 더해진 극강의 매운맛. 매운맛 최고 등급으로 소개됨.', 'Extreme heat with the aroma of curry. Introduced as the highest spice level in the lineup.', '加入咖喱香的极辣口味，被介绍为辣度最高等级。', 'カレーの香りが加わった超激辛。辛さ最高レベルとして紹介。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 7, '오뚜기 계란 수프면', 'Ottogi Egg Soup Ramen', '不倒翁鸡蛋汤面', 'オットギ エッグスープ麺', null, null, '맵지 않은 고소한 계란 국물. 아이·환자도 먹기 좋은 부드러운 맛으로 소개됨.', 'Mild, nutty egg broth with no spice. Introduced as gentle enough for children and those feeling unwell.', '不辣的香浓鸡蛋汤底，口感温和，适合儿童和病人食用。', '辛くない香ばしい卵スープ。子どもや体調不良の人にも食べやすいマイルドな味として紹介。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/'),
('vn', '🇻🇳', '베트남', 'Vietnam', '越南', 'ベトナム', 8, '삼양 마늘 크림라면', 'Samyang Garlic Cream Ramen', '三养大蒜奶油拉面', 'サムヤン ガーリッククリームラーメン', null, null, '크리미하고 마늘 향이 진한, 매운맛이 약한 라인. 크림 베이스를 좋아하는 사람에게 추천.', 'Creamy with a strong garlic aroma and mild spice. Recommended for those who enjoy cream-based flavors.', '奶油浓郁，大蒜香气十足，辣度较低，推荐给喜欢奶油口味的人。', 'クリーミーでガーリック香り豊か、辛さ控えめ。クリームベースが好きな人におすすめ。', '에디터 선정 (풍미·면발·인지도 기준)', 'Editor''s pick (flavor, texture & recognition)', '编辑精选（风味·面条·知名度基准）', '編集者セレクト（風味・麺・認知度基準）', 'https://bundaumamtomtienhai.vn/mi-goi-han-quoc-ngon-nhat/');
