-- 태국 인기 한국 라면 Top 10 데이터 삽입 (Thairath 편집자 추천 순서)

insert into country_picks (country_code, flag, country_ko, country_en, country_zh, country_ja, rank_num, name_ko, name_en, name_zh, name_ja, score, popularity, reason_ko, reason_en, reason_zh, reason_ja, source_ko, source_en, source_zh, source_ja, source_url) values
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 1, '삼양 불닭볶음면', 'Samyang Buldak Bokkeum Myeon', '三养火鸡炒面', 'サムヤン ブルダック炒め麺', null, null, '매운 걸 좋아하는 사람에게 추천되는 정통 매운맛. 참깨·김 토핑으로 풍미를 더함.', 'The go-to for spice lovers. Sesame and seaweed toppings add extra depth to the intense heat.', '辣味爱好者的首选，芝麻和海苔配料增添风味。', '辛党向けの本格的な辛さ。ごまと海苔トッピングで風味をアップ。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 2, '삼양 까르보 불닭볶음면', 'Samyang Carbonara Buldak', '三养卡波那拉火鸡炒面', 'サムヤン カルボナーラ ブルダック', null, null, '매운맛에 크리미한 까르보나라 소스가 더해진 조합. 태국인들 사이에서 인기 있는 맛으로 소개됨.', 'Spicy heat meets creamy carbonara sauce. Introduced as one of the most popular flavors among Thais.', '辣味与奶油卡波那拉酱的组合，被介绍为泰国人中最受欢迎的口味之一。', '辛さにクリーミーなカルボナーラソースが合わさった組み合わせ。タイ人の間で人気の味として紹介。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 3, '삼양라면 컵(스파이시)', 'Samyang Ramen Cup Spicy', '三养拉面杯装（辛辣味）', 'サムヤン ラーメン カップ（スパイシー）', null, null, '작은 컵 사이즈로 간편하게. 국물이 진하고 살짝 매콤해 매운 음식을 잘 못 먹는 사람에게도 추천.', 'Convenient cup size with a rich, mildly spicy broth. Recommended even for those who can''t handle intense heat.', '小巧杯装，方便携带。汤底浓郁微辣，不太能吃辣的人也适合。', '小さなカップサイズで手軽に。スープが濃くほんのり辛く、辛いものが苦手な人にもおすすめ。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 4, '농심 신라면', 'Nongshim Shin Ramyun', '农心辛拉面', '農心辛ラーメン', null, null, '한국·태국 모두에서 잘 팔리는 베스트셀러. 표고버섯 향 국물, 추가 조미 없이도 맛있다는 평. 김치와 함께 먹으면 더 좋다고 소개됨.', 'A bestseller in both Korea and Thailand. Shiitake-scented broth that''s great on its own — even better with kimchi.', '韩国和泰国都畅销的经典款。香菇风味汤底，无需额外调味也好吃，配泡菜更佳。', '韓国・タイ両国でベストセラー。しいたけ香るスープで追加調味不要。キムチと一緒に食べるとさらにおいしい。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 5, '유어스 오모리 김치찌개라면', 'YOUUS Omori Kimchi Jjigae Ramen', '오모리泡菜锅拉面', 'ユアース オモリ キムチチゲラーメン', null, null, '생김치가 별도로 포함돼 정통 김치찌개 맛을 낼 수 있어 호평. 김치찌개 본연의 맛을 라면으로 즐기고 싶은 사람에게 추천.', 'Comes with fresh kimchi separately, letting you recreate an authentic kimchi jjigae flavor. Great for anyone craving the real thing in ramen form.', '附带新鲜泡菜，能还原正宗泡菜锅口味，广受好评。想用拉面享受地道泡菜锅味道的人必试。', '生キムチが別添えで本格的なキムチチゲの味を再現できると好評。ラーメンで本物のキムチチゲを楽しみたい人におすすめ。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 6, '농심 앵그리 짜파구리 슈퍼스파이시', 'Nongshim Angry Chapaguri Super Spicy', '农心愤怒炸酱乌冬超辣', '農心 アングリー チャパグリ スーパースパイシー', null, null, '영화 〈기생충〉으로 유명해진 짜파게티+너구리 조합의 초매운맛 버전.', 'The ultra-spicy version of the Chapaguri combo — made famous by the film Parasite.', '因电影《寄生虫》走红的炸酱乌冬组合的超辣版本。', '映画『パラサイト』で有名になったチャパグリの超激辛バージョン。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 7, '농심 짜파게티', 'Nongshim Chapagetti', '农心炸酱意面', '農心チャパゲティ', null, null, '짜장 소스 라면의 대표주자. 맵지 않아 남녀노소 즐기기 좋음.', 'The classic Korean black bean sauce noodle. Not spicy at all — enjoyable for everyone.', '韩式炸酱面的代表，不辣，老少皆宜。', 'ジャージャー麺ラーメンの定番。辛くなく老若男女に人気。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 8, '농심 오징어 짬뽕라면', 'Nongshim Squid Jjamppong Ramen', '农心鱿鱼炒码面', '農心 イカ チャンポンラーメン', null, null, '해물짬뽕 라면. 국물이 진하고 살짝 매콤해 드라마 보며 먹기 좋다는 평.', 'A seafood jjamppong ramen with a rich, lightly spicy broth — perfect for drama-watching sessions.', '海鲜炒码面，汤底浓郁微辣，边看剧边吃最合适。', '海鮮チャンポンラーメン。スープが濃くほんのり辛く、ドラマを見ながら食べるのにぴったり。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 9, '오뚜기 치즈라면', 'Ottogi Cheese Ramen', '不倒翁芝士拉面', 'オットギ チーズラーメン', null, null, '치즈의 고소함과 은은한 매운맛의 조화. 매운 걸 못 먹는 사람도 즐기기 좋음. 햄·건조야채 포함.', 'Nutty cheese flavor with a gentle heat. Great for those who can''t handle spice. Comes with ham and dried vegetables.', '芝士香浓与微辣的完美搭配，不能吃辣的人也适合，附带火腿和干蔬菜。', 'チーズのコクとほんのりした辛さのハーモニー。辛いものが苦手な人にも最適。ハムと乾燥野菜入り。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387'),
('th', '🇹🇭', '태국', 'Thailand', '泰国', 'タイ', 10, '팔도 비빔면', 'Paldo Bibim Myeon', '八道拌面', 'パルド ビビン麺', null, null, '새콤달콤한 냉면 스타일. 정통 비빔면 맛을 잘 재현했다는 평.', 'Sweet and tangy cold noodle style. Praised for authentically recreating the taste of traditional bibimmyeon.', '酸甜冷面风格，被赞为很好地还原了正宗拌面口味。', '甘酸っぱい冷麺スタイル。本格的なビビン麺の味をよく再現していると好評。', 'Thairath 편집자 추천 순서', 'Thairath editorial recommendation order', 'Thairath编辑推荐顺序', 'Thairath編集者おすすめ順', 'https://www.thairath.co.th/shopping/food/1000387');
