-- 편의점 도시락 가이드용 dosirak_items 테이블 생성 (Supabase SQL 에디터에서 실행)
-- gimbap_items와 동일한 패턴: 다국어 텍스트 + 큐레이션 필드
-- 가격(price_krw)은 실제 조사 전 플레이스홀더(0)로 채워둠 — admin에서 실제 값으로 수정 필요

create table dosirak_items (
  id bigint generated always as identity primary key,
  order_num int not null default 0,
  name_ko text not null,
  name_en text,
  name_zh text,
  name_ja text,
  image_url text,
  flavor_desc_ko text,
  flavor_desc_en text,
  flavor_desc_zh text,
  flavor_desc_ja text,
  composition_ko text,
  composition_en text,
  composition_zh text,
  composition_ja text,
  allergen_note_ko text,
  allergen_note_en text,
  allergen_note_zh text,
  allergen_note_ja text,
  price_krw int,
  manufacturer_url text
);

-- 편의점 도시락 대표 종류 5종 (일반적으로 널리 알려진 구성 기준, 상품별 상세는 추후 admin에서 조사 후 입력)
insert into dosirak_items (order_num, name_ko, name_en, name_zh, name_ja, flavor_desc_ko, flavor_desc_en, flavor_desc_zh, flavor_desc_ja, composition_ko, composition_en, composition_zh, composition_ja, allergen_note_ko, allergen_note_en, allergen_note_zh, allergen_note_ja, price_krw) values
(1, '치킨마요 도시락', 'Chicken Mayo Bento', '鸡肉蛋黄酱便当', 'チキンマヨ弁当',
 '튀긴 치킨 조각에 마요네즈 소스를 얹은 구성. 짜지 않고 부드러워 외국인이 가장 무난하게 시도하는 도시락.',
 'Fried chicken pieces topped with mayo sauce. Mild and creamy — the safest first pick for first-timers.',
 '炸鸡块淋上蛋黄酱酱汁的组合，口味温和不咸，是外国游客最容易接受的入门款便当。',
 '揚げチキンにマヨネーズソースをかけた構成。塩気が少なくまろやかで、初めて食べる方に一番おすすめ。',
 '밥, 튀긴 치킨, 마요네즈 소스, 채소 반찬(단무지·나물 등) 1~2종.',
 'Rice, fried chicken, mayo sauce, and 1-2 side vegetables (pickled radish, namul, etc.).',
 '米饭、炸鸡、蛋黄酱酱汁、1~2种蔬菜小菜（腌萝卜、拌菜等）。',
 'ご飯、揚げチキン、マヨネーズソース、野菜のおかず（たくあん・ナムルなど）1〜2種。',
 '밀가루·계란(튀김옷), 계란(마요네즈) 함유. 알레르기 있으면 성분표 확인 필요.',
 'Contains wheat and egg (batter), egg (mayonnaise). Check the label if you have allergies.',
 '含有小麦、鸡蛋（炸衣）、鸡蛋（蛋黄酱）成分，过敏体质请确认成分表。',
 '小麦・卵（衣）、卵（マヨネーズ）を含みます。アレルギーがある方は成分表をご確認ください。',
 0),
(2, '제육볶음 도시락', 'Spicy Pork Bento', '辣炒猪肉便当', 'チェユクポックム弁当',
 '고추장 양념 돼지고기 볶음이 메인. 한국식 매콤달콤한 맛이 강해 매운맛에 거부감 없는 사람에게 추천.',
 'Stir-fried pork in spicy gochujang sauce as the main dish. Strongly sweet-and-spicy Korean style — recommend only if you can handle spice.',
 '以辣椒酱腌制的炒猪肉为主菜，韩式甜辣口味较浓，能吃辣的人推荐尝试。',
 'コチュジャン味の豚肉炒めがメイン。韓国式の甘辛い味が強いので、辛さが平気な方向け。',
 '밥, 매운 돼지고기 볶음, 채소 반찬(콩나물·김치 등) 1~2종.',
 'Rice, spicy stir-fried pork, and 1-2 side vegetables (bean sprouts, kimchi, etc.).',
 '米饭、辣炒猪肉、1~2种蔬菜小菜（豆芽、泡菜等）。',
 'ご飯、辛い豚肉炒め、野菜のおかず（豆もやし・キムチなど）1〜2種。',
 '돼지고기, 대두(고추장) 함유. 돼지고기 성분으로 할랄·힌두 식단 부적합.',
 'Contains pork and soybean (gochujang). Not suitable for halal or Hindu dietary restrictions due to pork.',
 '含有猪肉、大豆（辣椒酱）成分。因含猪肉不适合清真或印度教饮食。',
 '豚肉・大豆（コチュジャン）を含みます。豚肉成分のためハラール・ヒンドゥー教の食事制限には不向き。',
 0),
(3, '돈까스 도시락', 'Pork Cutlet Bento', '炸猪排便当', 'とんかつ弁当',
 '두툼한 돈까스에 소스를 곁들인 구성. 바삭한 튀김옷과 부드러운 고기 식감이 특징.',
 'Thick pork cutlet served with sauce. Known for its crispy batter and tender meat.',
 '厚实的炸猪排配以酱汁，外酥里嫩是其特色。',
 '厚切りとんかつにソースを添えた構成。サクサクの衣と柔らかい肉が特徴。',
 '밥, 돈까스, 돈까스 소스, 양배추 채, 채소 반찬 1종.',
 'Rice, pork cutlet, tonkatsu sauce, shredded cabbage, and 1 side vegetable.',
 '米饭、炸猪排、猪排酱汁、卷心菜丝、1种蔬菜小菜。',
 'ご飯、とんかつ、とんかつソース、千切りキャベツ、野菜のおかず1種。',
 '돼지고기, 밀가루·계란(튀김옷) 함유. 돼지고기 성분으로 할랄·힌두 식단 부적합.',
 'Contains pork, wheat and egg (batter). Not suitable for halal or Hindu dietary restrictions due to pork.',
 '含有猪肉、小麦、鸡蛋（炸衣）成分。因含猪肉不适合清真或印度教饮食。',
 '豚肉・小麦・卵（衣）を含みます。豚肉成分のためハラール・ヒンドゥー教の食事制限には不向き。',
 0),
(4, '고등어구이 도시락', 'Grilled Mackerel Bento', '烤鲭鱼便当', '焼き鯖弁当',
 '짭짤하게 구운 고등어가 메인. 생선 특유의 향이 있어 호불호가 갈릴 수 있음.',
 'Grilled mackerel with a salty flavor as the main dish. Has a distinct fish aroma that can be an acquired taste.',
 '咸香烤制的鲭鱼为主菜，带有鱼类特有的香气，可能会有明显的好恶差异。',
 '塩味で焼いた鯖がメイン。魚特有の香りがあるため好みが分かれることがあります。',
 '밥, 구운 고등어, 채소 반찬(무나물·김치 등) 1~2종.',
 'Rice, grilled mackerel, and 1-2 side vegetables (radish namul, kimchi, etc.).',
 '米饭、烤鲭鱼、1~2种蔬菜小菜（萝卜拌菜、泡菜等）。',
 'ご飯、焼き鯖、野菜のおかず（大根ナムル・キムチなど）1〜2種。',
 '어패류(고등어) 함유. 생선 알레르기 있으면 주의.',
 'Contains fish (mackerel). Caution advised for those with fish allergies.',
 '含有鱼类（鲭鱼）成分，鱼类过敏者请注意。',
 '魚介類（鯖）を含みます。魚アレルギーがある方はご注意ください。',
 0),
(5, '비빔밥 도시락', 'Bibimbap Bento', '拌饭便当', 'ビビンバ弁当',
 '나물과 고추장을 밥과 비벼 먹는 구성. 채소 비중이 높아 상대적으로 가벼운 한 끼.',
 'Rice mixed with seasoned vegetables and gochujang. Vegetable-heavy — a relatively light meal.',
 '将拌菜和辣椒酱与米饭拌匀食用，蔬菜比例较高，相对清爽的一餐。',
 'ナムルとコチュジャンをご飯と混ぜて食べる構成。野菜の比率が高く、比較的軽い一食。',
 '밥, 나물(콩나물·시금치 등) 여러 종, 고추장, 계란후라이(상품에 따라 포함).',
 'Rice, several types of seasoned vegetables (bean sprouts, spinach, etc.), gochujang, and a fried egg (varies by product).',
 '米饭、多种拌菜（豆芽、菠菜等）、辣椒酱、煎蛋（视产品而定）。',
 'ご飯、ナムル（豆もやし・ほうれん草など）数種、コチュジャン、目玉焼き（商品による）。',
 '대두(고추장), 참기름, 계란(포함 시) 함유. 채식 기준은 상품마다 다르므로 라벨 확인 필요.',
 'Contains soybean (gochujang), sesame oil, and egg (if included). Vegetarian suitability varies by product — check the label.',
 '含有大豆（辣椒酱）、香油、鸡蛋（如包含）成分。是否适合素食因产品而异，请确认标签。',
 '大豆（コチュジャン）・ごま油・卵（含む場合）を含みます。ベジタリアン対応は商品により異なるためラベルをご確認ください。',
 0);
