-- 편의점 삼각김밥 가이드용 gimbap_items 테이블 생성 (Supabase SQL 에디터에서 실행)
-- ramen_items와 동일한 패턴: 다국어 텍스트 + 큐레이션 필드
-- 가격(price_krw)은 실제 조사 전 플레이스홀더(0)로 채워둠 — admin에서 실제 값으로 수정 필요

create table gimbap_items (
  id bigint generated always as identity primary key,
  order_num int not null default 0,
  name_ko text not null,
  name_en text,
  name_zh text,
  name_ja text,
  image_url text,
  flavor_desc_ko text,
  flavor_desc_en text,
  flavor_desc_zh text,
  flavor_desc_ja text,
  allergen_note_ko text,
  allergen_note_en text,
  allergen_note_zh text,
  allergen_note_ja text,
  price_krw int,
  manufacturer_url text
);

-- 삼각김밥 대표 맛 5종 (일반적으로 널리 알려진 맛 기준, 상품별 상세는 추후 admin에서 조사 후 입력)
insert into gimbap_items (order_num, name_ko, name_en, name_zh, name_ja, flavor_desc_ko, flavor_desc_en, flavor_desc_zh, flavor_desc_ja, allergen_note_ko, allergen_note_en, allergen_note_zh, allergen_note_ja, price_krw) values
(1, '참치마요', 'Tuna Mayo', '金枪鱼蛋黄酱', 'ツナマヨ',
 '참치와 마요네즈를 버무린 속. 짜지 않고 부드러워 외국인이 가장 무난하게 시도하는 맛.',
 'Tuna mixed with mayonnaise. Mild and creamy — the safest first pick for first-timers.',
 '金枪鱼拌蛋黄酱馅料。口味温和不咸，是外国游客最容易接受的入门款。',
 'ツナとマヨネーズを和えた具材。塩気が少なくまろやかで、初めて食べる方に一番おすすめ。',
 '어패류(참치), 계란(마요네즈) 함유. 알레르기 있으면 성분표 확인 필요.',
 'Contains fish (tuna) and egg (mayonnaise). Check the label if you have allergies.',
 '含有鱼类（金枪鱼）、鸡蛋（蛋黄酱）成分，过敏体质请确认成分表。',
 '魚介類（ツナ）・卵（マヨネーズ）を含みます。アレルギーがある方は成分表をご確認ください。',
 0),
(2, '전주비빔', 'Jeonju Bibim', '全州拌饭', '全州ビビン',
 '고추장 양념 나물밥. 매콤달콤한 비빔밥 맛을 그대로 옮겨놓은 맛으로, 매운맛에 거부감 없는 사람에게 추천.',
 'Rice mixed with gochujang (chili paste) and seasoned vegetables — a bibimbap flavor in gimbap form. Recommend only if you can handle mild spice.',
 '拌有辣椒酱和蔬菜的米饭，重现了拌饭的味道，微辣，能吃辣的人推荐尝试。',
 'コチュジャンで和えたナムル入りご飯。ビビンバの味をそのまま再現。辛さが平気な方向け。',
 '대두(고추장), 참기름 함유. 채식 기준은 상품마다 다르므로 라벨 확인 필요.',
 'Contains soybean (gochujang) and sesame oil. Vegetarian suitability varies by product — check the label.',
 '含有大豆（辣椒酱）、香油成分。是否适合素食因产品而异，请确认标签。',
 '大豆（コチュジャン）・ごま油を含みます。ベジタリアン対応は商品により異なるためラベルをご確認ください。',
 0),
(3, '불고기', 'Bulgogi', '烤肉', 'プルコギ',
 '간장 양념 소고기(또는 돼지고기) 볶음 속. 한국식 단짠 양념 맛이 강한 편.',
 'Soy-marinated beef (or pork) filling. Strongly sweet-and-savory Korean style.',
 '酱油腌制的牛肉（或猪肉）炒制馅料，韩式甜咸口味较浓。',
 '醤油ダレの牛肉（または豚肉）炒め具材。韓国式の甘辛い味付けが特徴。',
 '육류(소고기 또는 돼지고기), 대두(간장) 함유. 할랄·채식 여부는 상품별 확인 필수.',
 'Contains meat (beef or pork) and soybean (soy sauce). Always check halal/vegetarian status per product.',
 '含有肉类（牛肉或猪肉）、大豆（酱油）成分。清真、素食是否适用需逐一确认产品。',
 '肉類（牛肉または豚肉）・大豆（醤油）を含みます。ハラール・ベジタリアン対応は商品ごとに要確認。',
 0),
(4, '스팸마요', 'Spam Mayo', '午餐肉蛋黄酱', 'スパムマヨ',
 '스팸(햄)과 마요네즈 조합. 짭짤하고 기름진 맛으로 호불호가 크지 않은 무난한 인기 맛.',
 'Spam (canned ham) with mayonnaise. Salty and rich — widely popular with broad appeal.',
 '午餐肉（火腿）与蛋黄酱的组合，咸香浓郁，是接受度较高的人气口味。',
 'スパム（ハム）とマヨネーズの組み合わせ。塩気があり濃厚な味で人気の定番。',
 '돼지고기(스팸), 계란(마요네즈) 함유. 돼지고기 성분으로 할랄·힌두 식단 부적합.',
 'Contains pork (Spam) and egg (mayonnaise). Not suitable for halal or Hindu dietary restrictions due to pork.',
 '含有猪肉（午餐肉）、鸡蛋（蛋黄酱）成分。因含猪肉不适合清真或印度教饮食。',
 '豚肉（スパム）・卵（マヨネーズ）を含みます。豚肉成分のためハラール・ヒンドゥー教の食事制限には不向き。',
 0),
(5, '멸치볶음', 'Stir-fried Anchovy', '炒鳀鱼', 'いりこ炒め',
 '짭짤하고 달콤하게 볶은 잔멸치 속. 한국인에게 익숙한 밑반찬 맛이라 외국인에게는 호불호가 갈릴 수 있음.',
 'Small dried anchovies stir-fried sweet and salty. A familiar Korean side-dish flavor that can be an acquired taste for first-timers.',
 '甜咸炒制的小鳀鱼馅料。是韩国人熟悉的小菜口味，外国游客可能会有明显的好恶差异。',
 '甘辛く炒めたいりこ（煮干し）の具材。韓国人には馴染み深い惣菜の味だが、外国人には好みが分かれる可能性あり。',
 '어패류(멸치) 함유.',
 'Contains fish (anchovy).',
 '含有鱼类（鳀鱼）成分。',
 '魚介類（いりこ）を含みます。',
 0);

-- "편의점 가이드" 그룹에 삼각김밥 가이드 페이지를 위한 카테고리 항목은 홈 화면(HomeScreen.tsx)에서 직접 카드로 연결하므로
-- jeju_items/jeju_categories 등록은 불필요 (독립 라우트 /guide/gimbap 사용)
