-- 편의점 줄김밥 가이드용 jul_gimbap_items 테이블 생성 (Supabase SQL 에디터에서 실행)
-- dosirak_items와 동일한 패턴: 다국어 텍스트 + 큐레이션 필드
-- 가격(price_krw)은 실제 조사 전 플레이스홀더(0)로 채워둠 — admin에서 실제 값으로 수정 필요

create table jul_gimbap_items (
  id bigint generated always as identity primary key,
  order_num int not null default 0,
  name_ko text not null,
  name_en text,
  name_zh text,
  name_ja text,
  image_url text,
  flavor_desc_ko text,
  flavor_desc_en text,
  flavor_desc_zh text,
  flavor_desc_ja text,
  composition_ko text,
  composition_en text,
  composition_zh text,
  composition_ja text,
  allergen_note_ko text,
  allergen_note_en text,
  allergen_note_zh text,
  allergen_note_ja text,
  price_krw int,
  manufacturer_url text
);

-- 편의점 줄김밥 대표 유형 4종 (일반적으로 널리 알려진 구성 기준, 상품별 상세는 추후 admin에서 조사 후 입력)
insert into jul_gimbap_items (order_num, name_ko, name_en, name_zh, name_ja, flavor_desc_ko, flavor_desc_en, flavor_desc_zh, flavor_desc_ja, composition_ko, composition_en, composition_zh, composition_ja, allergen_note_ko, allergen_note_en, allergen_note_zh, allergen_note_ja, price_krw) values
(1, '전주비빔김밥', 'Jeonju Bibim Gimbap', '全州拌饭紫菜卷', '全州ビビン海苔巻き',
 '고추장 양념 나물과 밥을 넣고 만 김밥. 매콤달콤한 맛으로 삼각김밥의 롱셀러 맛을 롤 형태로 즐길 수 있음.',
 'Rice roll filled with gochujang-seasoned vegetables. A sweet-and-spicy flavor — the roll version of a gimbap classic.',
 '用辣椒酱拌菜和米饭卷成的紫菜卷，甜辣口味，是饭团经典口味的卷状版本。',
 'コチュジャンで和えたナムルとご飯を巻いた海苔巻き。甘辛い味で、おにぎりの定番の味を巻き寿司スタイルで楽しめる。',
 '김, 밥, 나물(콩나물·시금치 등), 고추장, 계란지단, 단무지.',
 'Seaweed, rice, seasoned vegetables (bean sprouts, spinach, etc.), gochujang, egg strips, pickled radish.',
 '海苔、米饭、拌菜（豆芽、菠菜等）、辣椒酱、鸡蛋丝、腌萝卜。',
 '海苔、ご飯、ナムル（豆もやし・ほうれん草など）、コチュジャン、錦糸卵、たくあん。',
 '대두(고추장), 참기름, 계란 함유. 채식 기준은 상품마다 다르므로 라벨 확인 필요.',
 'Contains soybean (gochujang), sesame oil, and egg. Vegetarian suitability varies by product — check the label.',
 '含有大豆（辣椒酱）、香油、鸡蛋成分。是否适合素食因产品而异，请确认标签。',
 '大豆（コチュジャン）・ごま油・卵を含みます。ベジタリアン対応は商品により異なるためラベルをご確認ください。',
 0),
(2, '참치김밥', 'Tuna Gimbap', '金枪鱼紫菜卷', 'ツナ海苔巻き',
 '참치마요를 넣고 만 김밥. 짜지 않고 부드러워 처음 김밥을 시도하는 사람에게 무난한 맛.',
 'Rice roll filled with tuna mayo. Mild and creamy — a safe first pick for gimbap beginners.',
 '加入金枪鱼蛋黄酱卷成的紫菜卷，口味温和不咸，是初次尝试紫菜卷的理想选择。',
 'ツナマヨを巻いた海苔巻き。塩気が少なくまろやかで、初めて海苔巻きを試す方にもおすすめ。',
 '김, 밥, 참치마요, 당근, 시금치, 단무지.',
 'Seaweed, rice, tuna mayo, carrot, spinach, pickled radish.',
 '海苔、米饭、金枪鱼蛋黄酱、胡萝卜、菠菜、腌萝卜。',
 '海苔、ご飯、ツナマヨ、にんじん、ほうれん草、たくあん。',
 '어패류(참치), 계란(마요네즈) 함유. 알레르기 있으면 성분표 확인 필요.',
 'Contains fish (tuna) and egg (mayonnaise). Check the label if you have allergies.',
 '含有鱼类（金枪鱼）、鸡蛋（蛋黄酱）成分，过敏体质请确认成分表。',
 '魚介類（ツナ）・卵（マヨネーズ）を含みます。アレルギーがある方は成分表をご確認ください。',
 0),
(3, '진짜 소불고기김밥', 'Beef Bulgogi Gimbap', '真牛肉烤肉紫菜卷', '本格牛焼肉海苔巻き',
 '간장 양념 소불고기를 넣고 만 김밥. 고기가 들어가 든든하고, 한국식 단짠 양념 맛이 강한 편.',
 'Rice roll filled with soy-marinated beef bulgogi. Hearty and filling with a strong sweet-savory Korean flavor.',
 '加入酱油腌制牛肉烤肉卷成的紫菜卷，有肉更饱腹，韩式甜咸口味较浓。',
 '醤油ダレの牛焼肉を巻いた海苔巻き。肉が入って食べ応えがあり、韓国式の甘辛い味が強め。',
 '김, 밥, 소불고기, 당근, 시금치, 단무지.',
 'Seaweed, rice, beef bulgogi, carrot, spinach, pickled radish.',
 '海苔、米饭、牛肉烤肉、胡萝卜、菠菜、腌萝卜。',
 '海苔、ご飯、牛焼肉、にんじん、ほうれん草、たくあん。',
 '육류(소고기), 대두(간장) 함유.',
 'Contains meat (beef) and soybean (soy sauce).',
 '含有肉类（牛肉）、大豆（酱油）成分。',
 '肉類（牛肉）・大豆（醤油）を含みます。',
 0),
(4, '치즈김밥', 'Cheese Gimbap', '芝士紫菜卷', 'チーズ海苔巻き',
 '치즈를 넣고 만 김밥. 고소하고 부드러운 맛으로 매운 것을 못 먹는 사람에게 추천.',
 'Rice roll filled with cheese. Mild and creamy — recommended for those who can''t handle spicy food.',
 '加入芝士卷成的紫菜卷，香浓柔和，推荐给不能吃辣的人。',
 'チーズを巻いた海苔巻き。まろやかで優しい味なので、辛いものが苦手な方におすすめ。',
 '김, 밥, 치즈, 당근, 시금치, 단무지.',
 'Seaweed, rice, cheese, carrot, spinach, pickled radish.',
 '海苔、米饭、芝士、胡萝卜、菠菜、腌萝卜。',
 '海苔、ご飯、チーズ、にんじん、ほうれん草、たくあん。',
 '우유(치즈) 함유.',
 'Contains milk (cheese).',
 '含有牛奶（芝士）成分。',
 '牛乳（チーズ）を含みます。',
 0);
