-- 편의점 라면 목록 일괄 추가 (Supabase SQL 에디터에서 실행)
-- 신라면 컵은 이미 입력되어 있으므로 제외

insert into ramen_items (
  order_num, name_ko, name_en, name_zh, name_ja,
  flavor_desc_ko, flavor_desc_en, flavor_desc_zh, flavor_desc_ja,
  comparison_ko, comparison_en, comparison_zh, comparison_ja,
  popularity_ko, popularity_en, popularity_zh, popularity_ja,
  texture_ko, texture_en, texture_zh, texture_ja,
  prep_time, spicy_level,
  noodle_type, soup_type, heat_source, price_krw
) values

-- ───────────────────────────────────────────────
-- 농심 컵라면
-- ───────────────────────────────────────────────
(2, '육개장 사발면', 'Yukgaejang Sabal', '육개장사발면', 'ユッケジャンサバル',
 '얼큰한 소고기 육수에 고사리와 대파가 들어간 전통 해장국 스타일',
 'Spicy beef broth with fernbrake and green onion, traditional Korean hangover soup style',
 '辣牛肉汤配蕨菜和大葱，传统韩国解酒汤风味',
 '辛い牛肉スープにわらびとネギが入った伝統的な韓国スタイル',
 '매운 토마토 비프 수프와 비슷하지만 더 진하고 한국적인 풍미',
 'Similar to spicy tomato beef soup but deeper and more Korean in flavor',
 '类似辣番茄牛肉汤，但更浓郁、更具韩国风味',
 '辛いトマトビーフスープに似ているが、より深みがあり韓国らしい風味',
 '동남아시아, 한국 현지인이 즐겨 먹는 국민 해장라면',
 'Beloved hangover ramen enjoyed by Southeast Asians and Korean locals',
 '深受东南亚人和韩国本地人喜爱的解酒拉面',
 '東南アジアと韓国人に愛される定番二日酔いラーメン',
 '부드러운 당면면과 풍성한 건더기',
 'Soft noodles with generous toppings',
 '软滑面条配丰富配料',
 '柔らかい麺とたっぷりの具材',
 4, 3, 'cup', 'soup', 'hot_water', 1300),

(3, '너구리 컵', 'Neoguri Cup', '浣熊杯面', 'ノグリカップ',
 '쫄깃한 우동면에 매콤한 해물 국물, 다시마가 들어간 깊은 맛',
 'Chewy udon-style noodles in spicy seafood broth with deep kelp flavor',
 '劲道乌冬面配辛辣海鲜汤底，含海带的深层鲜味',
 'モチモチのうどん麺に辛い海鮮スープ、昆布の深い旨味',
 '일본 우동과 한국 해물탕을 합친 것 같은 맛',
 'Like a fusion of Japanese udon and Korean seafood soup',
 '像日式乌冬面和韩式海鲜汤的融合',
 '日本のうどんと韓国の海鮮鍋を合わせたような味',
 '일본, 동남아시아에서 한국 대표 라면으로 알려짐',
 'Known as a representative Korean ramen in Japan and Southeast Asia',
 '在日本和东南亚以代表性韩国拉面著称',
 '日本や東南アジアで代表的な韓国ラーメンとして知られる',
 '두꺼운 면이 쫄깃하고 탱탱함',
 'Thick noodles with chewy, bouncy texture',
 '厚实面条，劲道有弹性',
 '太めの麺でモチモチとした食感',
 4, 2, 'cup', 'soup', 'hot_water', 1300),

(4, '짜파게티 컵', 'Chapaghetti Cup', '炸酱意面杯', 'チャパゲティカップ',
 '짜장 소스와 스파게티를 합친 한국식 블랙빈 누들',
 'Korean-style black bean noodles combining jajang sauce and spaghetti',
 '韩式黑豆酱面，融合炸酱和意面元素',
 'ジャージャーソースとスパゲッティを組み合わせた韓国式黒豆麺',
 '중국 짜장면에서 영감을 받은 한국만의 독특한 블랙빈 파스타',
 'Unique Korean black bean pasta inspired by Chinese jajangmyeon',
 '受中国炸酱面启发的独特韩国黑豆意面',
 '中国のジャージャー麺にインスパイアされた韓国独自の黒豆パスタ',
 '한국, 중국, 동남아시아에서 꾸준한 인기',
 'Consistently popular in Korea, China, and Southeast Asia',
 '在韩国、中国和东南亚持续受欢迎',
 '韓国・中国・東南アジアで継続的に人気',
 '부드럽고 쫄깃한 면에 진한 짜장 소스',
 'Soft and chewy noodles with rich black bean sauce',
 '软糯有嚼劲的面条配浓郁黑豆酱',
 '柔らかくモチモチの麺に濃厚なジャージャーソース',
 3, 0, 'cup', 'dry', 'hot_water', 1300),

(5, '오징어짬뽕 컵', 'Squid Jjamppong Cup', '鱿鱼炒码面杯', 'イカチャンポンカップ',
 '오징어가 들어간 얼큰한 해물 짬뽕 국물',
 'Spicy seafood jjamppong broth with real squid',
 '含鱿鱼的辛辣海鲜炒码面汤底',
 'イカ入りの辛い海鮮チャンポンスープ',
 '중국 짬뽕에서 유래한 한국식 매운 해물면',
 'Korean-style spicy seafood noodles derived from Chinese champon',
 '源自中式炒码面的韩式辣海鲜面',
 '中国のちゃんぽんに由来する韓国式辛い海鮮麺',
 '해산물을 즐기는 동남아시아 관광객에게 인기',
 'Popular among Southeast Asian tourists who enjoy seafood',
 '深受喜爱海鲜的东南亚游客欢迎',
 '海鮮好きの東南アジア観光客に人気',
 '탱글탱글한 오징어와 쫄깃한 면',
 'Tender squid pieces with chewy noodles',
 '弹牙鱿鱼配劲道面条',
 'プリプリのイカとモチモチの麺',
 3, 3, 'cup', 'soup', 'hot_water', 1500),

(6, '건면 새우탕 컵', 'Shrimp Soup Cup (Dried Noodle)', '虾汤杯面（干面）', '건면えびたんカップ',
 '담백하고 깔끔한 새우 국물에 건면을 사용해 칼로리가 낮음',
 'Light and clean shrimp broth with dried noodles and lower calories',
 '清淡鲜美的虾汤配干面，热量较低',
 'あっさりした海老スープに乾麺使用でカロリー控えめ',
 '가벼운 일본식 새우 라면과 비슷한 느낌',
 'Similar to light Japanese-style shrimp ramen',
 '类似清淡的日式虾味拉面',
 '軽い日本式えびラーメンに近い感覚',
 '건강을 중시하는 일본, 중국 관광객에게 인기',
 'Popular among health-conscious Japanese and Chinese tourists',
 '受注重健康的日本和中国游客欢迎',
 '健康志向の日本・中国人観光客に人気',
 '얇고 가벼운 건면, 술술 넘어가는 식감',
 'Thin and light dried noodles with smooth texture',
 '细腻轻盈的干面，口感顺滑',
 '細くて軽い乾麺、つるっとした食感',
 3, 1, 'cup', 'soup', 'hot_water', 1500),

-- ───────────────────────────────────────────────
-- 오뚜기 컵라면
-- ───────────────────────────────────────────────
(7, '진라면 매운맛 컵', 'Jin Ramen Spicy Cup', '真拉面辣味杯', '眞ラーメン辛口カップ',
 '진하고 얼큰한 빨간 국물, 신라면보다 부드러운 매운맛',
 'Rich and spicy red broth, milder heat than Shin Ramyun',
 '浓郁辛辣的红色汤底，比辛拉面辣度更温和',
 '濃くてピリ辛の赤いスープ、辛ラーメンより穏やかな辛さ',
 '신라면보다 덜 맵고 더 감칠맛 있는 한국 라면 입문용',
 'Less spicy than Shin Ramyun with more umami, perfect for ramen beginners',
 '比辛拉面辣度低，鲜味更足，适合拉面新手',
 '辛ラーメンより辛さ控えめでうま味豊か、入門にぴったり',
 '한국 내수 시장에서 신라면과 함께 가장 많이 팔리는 라면',
 'One of the best-selling ramen in Korea alongside Shin Ramyun',
 '与辛拉面并列韩国销量最高的拉面之一',
 '辛ラーメンと並んで韓国で最も売れているラーメン',
 '쫄깃하고 탱탱한 면발',
 'Chewy and springy noodles',
 '劲道有弹性的面条',
 'モチモチとした弾力ある麺',
 3, 2, 'cup', 'soup', 'hot_water', 1100),

(8, '진라면 순한맛 컵', 'Jin Ramen Mild Cup', '真拉面温和味杯', '眞ラーメン甘口カップ',
 '부드럽고 순한 황금빛 국물, 매운 음식이 익숙하지 않은 분께 추천',
 'Smooth and mild golden broth, recommended for those not used to spicy food',
 '柔和顺滑的金色汤底，推荐给不习惯辛辣的人',
 '穏やかで優しいゴールデンスープ、辛い食べ物に慣れていない方におすすめ',
 '닭고기 국물 라면과 비슷하지만 더 감칠맛 있는 한국식',
 'Similar to chicken broth ramen but with more Korean-style umami',
 '类似鸡肉汤拉面，但具有更多韩式鲜味',
 '鶏ガラスープラーメンに似ているが、より韓国式のうま味がある',
 '매운 음식을 못 먹는 외국인 관광객에게 특히 추천',
 'Especially recommended for foreign tourists who cannot eat spicy food',
 '特别推荐给不能吃辣的外国游客',
 '辛い食べ物が苦手な外国人観光客に特におすすめ',
 '부드럽고 매끄러운 면발',
 'Soft and smooth noodles',
 '软糯顺滑的面条',
 '柔らかくなめらかな麺',
 3, 0, 'cup', 'soup', 'hot_water', 1100),

(9, '열라면 컵', 'Yeol Ramen Cup', '热拉面杯', '烈ラーメンカップ',
 '강렬하고 화끈한 매운맛, 고추 베이스의 진한 국물',
 'Intense and fiery spiciness with rich chili-based broth',
 '强烈火辣的辣味，浓郁辣椒为底的汤头',
 '強烈でホットな辛さ、唐辛子ベースの濃いスープ',
 '핫소스를 넣은 스파이시 누들수프와 비슷한 강렬한 매운맛',
 'Intense heat similar to spicy noodle soup with hot sauce',
 '类似加入辣酱的辣味面汤，辣度强烈',
 'ホットソースを加えた辛いヌードルスープに似た強烈な辛さ',
 '매운 음식 도전을 좋아하는 외국인 관광객에게 인기',
 'Popular among foreign tourists who love spicy food challenges',
 '受喜欢挑战辣食的外国游客欢迎',
 '辛い食べ物に挑戦したい外国人観光客に人気',
 '쫄깃한 면발과 얼큰한 국물',
 'Chewy noodles with fiery broth',
 '劲道面条配火辣汤底',
 'モチモチ麺と辛い出汁',
 3, 4, 'cup', 'soup', 'hot_water', 1100),

-- ───────────────────────────────────────────────
-- 삼양 컵라면
-- ───────────────────────────────────────────────
(10, '불닭볶음면 컵', 'Buldak Bokkeummyeon Cup', '火鸡面杯', 'ブルダック炒め麺カップ',
 'SNS에서 전 세계적으로 유명한 초극매운 닭볶음 소스 볶음면',
 'Globally famous on social media, extremely spicy stir-fried chicken sauce noodles',
 '在社交媒体上享誉全球的超辣鸡肉酱炒面',
 'SNSで世界的に有名な超激辛チキンソース炒め麺',
 '스리라차의 3~4배 수준의 매운맛, 핫윙 소스보다 강렬',
 '3-4x spicier than Sriracha, more intense than hot wing sauce',
 '辣度是是辣椒酱的3-4倍，比辣翅酱更强烈',
 'スリラチャの3〜4倍の辛さ、ホットウィングソースより強烈',
 '전 세계 60개국 이상 수출, 외국인 라면 도전 영상으로 유명',
 'Exported to 60+ countries, famous for foreign challenge videos',
 '出口60多个国家，以外国人挑战视频闻名',
 '60カ国以上に輸出、外国人チャレンジ動画で有名',
 '쫄깃한 면에 달콤하고 매운 닭볶음 소스',
 'Chewy noodles with sweet and spicy stir-fried chicken sauce',
 '劲道面条配甜辣鸡肉酱',
 'モチモチ麺に甘辛チキンソース',
 3, 5, 'cup', 'dry', 'hot_water', 1800),

(11, '까르보 불닭볶음면 컵', 'Carbo Buldak Cup', '卡邦尼火鸡面杯', 'カルボブルダックカップ',
 '불닭 소스에 크리미한 까르보나라 소스를 더한 순한 버전',
 'Milder version combining buldak sauce with creamy carbonara sauce',
 '在火鸡面酱基础上加入奶油培根酱的温和版本',
 'ブルダックソースにクリーミーなカルボナーラソースを加えたマイルドバージョン',
 '까르보나라 파스타와 한국 매운 소스의 퓨전',
 'Fusion of carbonara pasta and Korean spicy sauce',
 '培根意面和韩式辣酱的融合',
 'カルボナーラパスタと韓国辛いソースのフュージョン',
 '불닭이 너무 매운 외국인에게 입문용으로 추천',
 'Recommended as an entry point for foreigners who find original buldak too spicy',
 '推荐给觉得原版火鸡面太辣的外国人作为入门选择',
 '元祖ブルダックが辛すぎる外国人への入門としておすすめ',
 '크리미하고 쫄깃한 면발',
 'Creamy and chewy noodles',
 '奶香劲道的面条',
 'クリーミーでモチモチの麺',
 3, 3, 'cup', 'dry', 'hot_water', 1800),

(12, '나가사끼 짬뽕 컵', 'Nagasaki Jjamppong Cup', '长崎炒码面杯', '長崎チャンポンカップ',
 '일본 나가사끼 짬뽕에서 영감을 받은 담백하고 풍부한 해물 국물',
 'Mild and rich seafood broth inspired by Japanese Nagasaki champon',
 '受日本长崎炒码面启发的清淡浓郁海鲜汤底',
 '日本の長崎ちゃんぽんにインスパイアされた、あっさり豊かな海鮮スープ',
 '일본 나가사끼 짬뽕과 매우 유사한 맛',
 'Very similar taste to Japanese Nagasaki champon',
 '与日本长崎炒码面味道非常相似',
 '日本の長崎ちゃんぽんと非常に似た味',
 '일본 관광객에게 특히 친숙하고 인기 있는 제품',
 'Especially familiar and popular among Japanese tourists',
 '在日本游客中尤其亲切和受欢迎',
 '日本人観光客に特になじみがあり人気の商品',
 '풍성한 건더기와 부드러운 면',
 'Generous toppings with soft noodles',
 '配料丰富，面条柔滑',
 '具材たっぷりで柔らかい麺',
 3, 1, 'cup', 'soup', 'hot_water', 1500),

-- ───────────────────────────────────────────────
-- 팔도 컵라면
-- ───────────────────────────────────────────────
(13, '왕뚜껑', 'Wang Ttukkeong', '王盖面', 'ワントゥッコン',
 '넉넉한 사이즈의 뚜껑을 접시로 활용하는 독특한 컵라면, 얼큰한 국물',
 'Uniquely designed cup ramen where the large lid is used as a bowl, spicy broth',
 '独特设计，大盖子可用作碗的杯面，辛辣汤底',
 '大きな蓋をお皿として使うユニークなカップラーメン、ピリ辛スープ',
 '뚜껑을 접시로 쓰는 아이디어가 신기한 한국만의 독특한 컵라면',
 'Uniquely Korean cup ramen with the novel idea of using the lid as a plate',
 '用盖子作碗的创意，独具韩国特色的杯面',
 '蓋をお皿として使うアイデアが面白い韓国独自のカップラーメン',
 '편의점 컵라면 중 가장 큰 사이즈로 한국 현지인에게 인기',
 'The largest cup ramen at convenience stores, popular among Korean locals',
 '便利店杯面中尺寸最大，深受韩国本地人喜爱',
 'コンビニカップラーメンの中で最大サイズ、韓国人に人気',
 '굵고 쫄깃한 면발',
 'Thick and chewy noodles',
 '粗壮劲道的面条',
 '太くてモチモチの麺',
 4, 2, 'cup', 'soup', 'hot_water', 1500),

(14, '도시락', 'Dosirak', '饭盒面', 'ドシラク',
 '작고 휴대하기 편한 사이즈, 담백한 국물 맛',
 'Small and portable size with mild, clean broth',
 '小巧便携，汤底清淡爽口',
 '小さくて持ち運びやすいサイズ、あっさりしたスープ',
 '일본 소바나 가벼운 라면과 비슷한 담백함',
 'Similar mildness to Japanese soba or light ramen',
 '类似日式荞麦面或清淡拉面的温和口感',
 '日本のそばや軽いラーメンに似たあっさり感',
 '러시아, 구소련권 국가에서 가장 유명한 한국 라면',
 'The most famous Korean ramen in Russia and former Soviet countries',
 '在俄罗斯和前苏联国家最著名的韩国拉面',
 'ロシアと旧ソ連諸国で最も有名な韓国ラーメン',
 '얇고 부드러운 면발',
 'Thin and soft noodles',
 '细腻柔软的面条',
 '細くて柔らかい麺',
 3, 1, 'cup', 'soup', 'hot_water', 1000),

-- ───────────────────────────────────────────────
-- 농심 봉지라면
-- ───────────────────────────────────────────────
(15, '신라면', 'Shin Ramyun', '辛拉面', '辛ラーメン',
 '맵고 진한 소고기 국물, 한국을 대표하는 국민 라면',
 'Spicy and rich beef broth, Korea''s most iconic national ramen',
 '辛辣浓郁的牛肉汤底，韩国最具代表性的国民拉面',
 '辛くて濃い牛肉スープ、韓国を代表する国民的ラーメン',
 '스리라차 소스의 매운맛과 비슷하지만 더 깊고 진한 맛',
 'Similar heat to Sriracha but deeper and richer in flavor',
 '辣度类似辣椒酱但风味更深厚浓郁',
 'スリラチャに似た辛さだが、より深みがある',
 '전 세계 100개국 이상 수출, 글로벌 판매 1위 한국 라면',
 'Exported to 100+ countries, the #1 globally sold Korean ramen',
 '出口100多个国家，全球销量第一的韩国拉面',
 '100カ国以上に輸出、世界販売No.1韓国ラーメン',
 '쫄깃하고 탱탱한 면발',
 'Chewy and springy noodles',
 '劲道有弹性的面条',
 'モチモチとした弾力ある麺',
 4, 3, 'bag', 'soup', 'stovetop', 1000),

(16, '짜파게티', 'Chapaghetti', '炸酱意面', 'チャパゲティ',
 '짜장 소스와 스파게티가 결합된 한국식 블랙빈 볶음면, 영화 기생충으로 유명',
 'Korean-style black bean stir-fried noodles combining jajang and spaghetti, famous from the movie Parasite',
 '韩式黑豆炒面，融合炸酱和意面，因电影《寄生虫》而闻名',
 'ジャージャーソースとスパゲッティを融合した韓国式黒豆炒め麺、映画「パラサイト」で有名',
 '중국 짜장면과 이탈리아 파스타의 한국식 퓨전',
 'Korean fusion of Chinese jajangmyeon and Italian pasta',
 '中式炸酱面与意式面条的韩国式融合',
 '中国のジャージャー麺とイタリアのパスタの韓国式フュージョン',
 '영화 기생충 이후 전 세계적으로 관심 급증',
 'Global interest surged after the movie Parasite',
 '电影《寄生虫》后全球关注度急剧上升',
 '映画「パラサイト」後、世界的に注目が急増',
 '부드럽고 쫄깃한 면에 진한 짜장 소스',
 'Soft chewy noodles with rich black bean sauce',
 '软糯劲道的面条配浓郁黑豆酱',
 '柔らかくモチモチの麺に濃厚な黒豆ソース',
 5, 0, 'bag', 'dry', 'stovetop', 1600),

(17, '안성탕면', 'Anseongtangmyeon', '安城汤面', 'アンソンタンミョン',
 '구수하고 부드러운 된장 베이스의 담백한 국물',
 'Savory and mild doenjang (soybean paste) based broth',
 '香浓柔和的大酱汤底，口味清淡',
 '香ばしく穏やかな味噌ベースのあっさりしたスープ',
 '일본 미소라멘과 비슷하지만 더 한국적인 구수함',
 'Similar to Japanese miso ramen but with a more Korean savory depth',
 '类似日式味噌拉面，但具有更多韩式醇香',
 '日本の味噌ラーメンに似ているが、より韓国的な香ばしさ',
 '매운 음식을 못 먹는 외국인과 어린이에게 추천',
 'Recommended for foreigners and children who cannot eat spicy food',
 '推荐给不能吃辣的外国游客和儿童',
 '辛い食べ物が苦手な外国人や子供におすすめ',
 '부드럽고 얇은 면발',
 'Soft and thin noodles',
 '柔软细腻的面条',
 '柔らかく細い麺',
 4, 1, 'bag', 'soup', 'stovetop', 1000),

(18, '너구리', 'Neoguri', '浣熊面', 'ノグリ',
 '두꺼운 우동 스타일 면에 얼큰한 해물 국물, 다시마가 핵심',
 'Thick udon-style noodles in spicy seafood broth, kelp is the key ingredient',
 '厚实乌冬风格面条配辛辣海鲜汤底，海带是关键食材',
 '太いうどんスタイルの麺に辛い海鮮スープ、昆布がポイント',
 '일본 우동과 한국 해물탕을 합친 독특한 맛',
 'Unique taste combining Japanese udon and Korean seafood soup',
 '融合日式乌冬面和韩式海鲜汤的独特口味',
 '日本のうどんと韓国の海鮮鍋を合わせた独特な味',
 '짜파게티와 섞어 먹는 짜파구리(너구리+짜파게티)로도 유명',
 'Also famous as Jjapaghuri (Neoguri + Chapaghetti) mixed together',
 '也因混合食用짜파구리（浣熊面+炸酱意面）而闻名',
 'ノグリとチャパゲティを混ぜたジャパグリとしても有名',
 '두껍고 탱탱한 면, 씹는 맛이 좋음',
 'Thick and springy noodles with satisfying chew',
 '粗壮弹牙的面条，嚼劲十足',
 '太くて弾力ある麺、噛み応えがある',
 5, 2, 'bag', 'soup', 'stovetop', 1000),

(19, '신라면 블랙', 'Shin Ramyun Black', '辛拉面黑', '辛ラーメンブラック',
 '신라면의 프리미엄 버전, 설렁탕 스타일의 진하고 깊은 소고기 사골 국물',
 'Premium version of Shin Ramyun with rich seolleongtang-style beef bone broth',
 '辛拉面的高级版，浓郁的雪浓汤风格牛骨汤底',
 '辛ラーメンのプレミアム版、コムタンスタイルの濃厚な牛骨スープ',
 '진한 프렌치어니언 수프와 소고기 국물을 합친 것 같은 깊은 맛',
 'Deep flavor like a combination of rich French onion soup and beef broth',
 '像浓郁法式洋葱汤与牛肉汤的结合，味道深厚',
 '濃厚なフレンチオニオンスープと牛骨スープを合わせたような深みのある味',
 '뉴욕타임스가 선정한 세계 최고의 인스턴트라면 중 하나',
 'Named one of the world''s best instant noodles by the New York Times',
 '被《纽约时报》评为世界最佳方便面之一',
 'ニューヨーク・タイムズが選んだ世界最高のインスタントラーメンの一つ',
 '신라면보다 더 두껍고 쫄깃한 프리미엄 면발',
 'Thicker and chewier premium noodles than regular Shin Ramyun',
 '比普通辛拉面更厚实、更有嚼劲的高级面条',
 '辛ラーメンより太くてモチモチなプレミアム麺',
 5, 3, 'bag', 'soup', 'stovetop', 1500),

(20, '짜왕', 'Jjajanwang', '炸酱王', 'チャワン',
 '짜장라면의 프리미엄 버전, 굵은 면과 진한 짜장 소스',
 'Premium jajang ramen with thick noodles and rich black bean sauce',
 '炸酱拉面的高级版，粗面条配浓郁黑豆酱',
 'ジャージャーラーメンのプレミアム版、太い麺と濃厚な黒豆ソース',
 '중국 프리미엄 짜장면과 비슷한 수준의 맛',
 'Similar quality to premium Chinese jajangmyeon',
 '与高档中式炸酱面品质相当的口味',
 '本格的な中国のジャージャー麺に近いクオリティ',
 '짜장라면 카테고리에서 가장 프리미엄으로 인정받는 제품',
 'The most premium product recognized in the jajang ramen category',
 '在炸酱拉面品类中公认最高端的产品',
 'ジャージャーラーメンカテゴリで最もプレミアムと認められる商品',
 '두꺼운 면이 소스를 잘 흡수해 진한 맛',
 'Thick noodles absorb the sauce well for rich flavor',
 '粗面条充分吸收酱汁，味道浓郁',
 '太い麺がソースをよく吸い込み濃厚な味わい',
 5, 0, 'bag', 'dry', 'stovetop', 1500),

-- ───────────────────────────────────────────────
-- 오뚜기 봉지라면
-- ───────────────────────────────────────────────
(21, '진라면 매운맛', 'Jin Ramen Spicy', '真拉面辣味', '眞ラーメン辛口',
 '한국에서 두 번째로 많이 팔리는 라면, 진하고 얼큰한 빨간 국물',
 'Second best-selling ramen in Korea, rich and spicy red broth',
 '韩国销量第二的拉面，浓郁辛辣的红色汤底',
 '韓国で2番目に売れているラーメン、濃くてピリ辛の赤いスープ',
 '신라면보다 덜 맵고 더 부드러운 한국 라면 입문용',
 'Less spicy than Shin Ramyun, perfect entry-level Korean ramen',
 '比辛拉面辣度低，是入门韩国拉面的最佳选择',
 '辛ラーメンより辛さ控えめ、韓国ラーメン入門に最適',
 '국내 판매 2위, 신라면과 함께 한국 라면의 양대 산맥',
 'Domestic sales #2, one of Korea''s two biggest ramen brands with Shin Ramyun',
 '国内销量第二，与辛拉面并列韩国两大拉面品牌',
 '国内販売2位、辛ラーメンと並ぶ韓国ラーメンの二大ブランド',
 '쫄깃하고 매끄러운 면발',
 'Chewy and smooth noodles',
 '劲道顺滑的面条',
 'モチモチでなめらかな麺',
 4, 2, 'bag', 'soup', 'stovetop', 1000),

(22, '진라면 순한맛', 'Jin Ramen Mild', '真拉面温和味', '眞ラーメン甘口',
 '황금빛 담백한 국물, 한국 라면 중 가장 순한 맛 중 하나',
 'Golden mild broth, one of the mildest among Korean ramen',
 '金色清淡汤底，韩国拉面中最温和的口味之一',
 '黄金色のあっさりスープ、韓国ラーメンの中で最も辛さ控えめの一つ',
 '일본 시오라멘이나 담백한 치킨 누들 수프와 비슷한 느낌',
 'Similar to Japanese shio ramen or mild chicken noodle soup',
 '类似日式盐味拉面或清淡鸡肉面汤',
 '日本の塩ラーメンや薄味のチキンヌードルスープに近い感じ',
 '매운 음식을 못 먹는 전 세계 모든 관광객에게 추천',
 'Recommended for tourists from around the world who cannot eat spicy food',
 '推荐给全球所有不能吃辣的游客',
 '辛い食べ物が苦手な世界中の観光客におすすめ',
 '부드럽고 가는 면발',
 'Soft and thin noodles',
 '柔软细腻的面条',
 '柔らかく細い麺',
 4, 0, 'bag', 'soup', 'stovetop', 1000),

(23, '참깨라면', 'Sesame Ramen', '芝麻拉面', 'ごまラーメン',
 '고소한 참깨 향이 가득한 부드럽고 담백한 국물',
 'Mild and smooth broth packed with nutty sesame fragrance',
 '充满香浓芝麻香气的柔和清淡汤底',
 'ナッツのようなごまの香りが広がる、まろやかであっさりしたスープ',
 '일본 참깨 라멘과 매우 비슷하지만 더 가벼운 느낌',
 'Very similar to Japanese sesame ramen but lighter',
 '与日式芝麻拉面非常相似，但口感更清淡',
 '日本のごまラーメンに非常に似ているが、より軽い感じ',
 '참깨를 즐기는 일본, 중국 관광객에게 특히 인기',
 'Especially popular among Japanese and Chinese tourists who enjoy sesame',
 '在喜爱芝麻的日本和中国游客中特别受欢迎',
 'ごまが好きな日本・中国人観光客に特に人気',
 '부드럽고 가는 면발에 고소한 국물',
 'Soft thin noodles with nutty broth',
 '柔软细面配香浓汤底',
 '柔らかく細い麺に香ばしいスープ',
 3, 1, 'bag', 'soup', 'stovetop', 1000),

(24, '열라면', 'Yeol Ramen', '烈拉面', '烈ラーメン',
 '강렬하고 화끈한 매운맛의 빨간 국물 라면',
 'Intensely fiery and spicy red broth ramen',
 '强烈火辣的红色汤底拉面',
 '強烈でホットな辛い赤スープラーメン',
 '핫소스를 베이스로 한 강렬한 매운 수프',
 'Intensely spicy soup with hot sauce base',
 '以辣酱为底料的强烈辣味汤',
 'ホットソースベースの強烈な辛いスープ',
 '매운 음식 마니아 외국인에게 인기있는 도전 라면',
 'Popular challenge ramen among foreign spicy food enthusiasts',
 '受外国辣食爱好者欢迎的挑战性拉面',
 '外国人の辛さマニアに人気のチャレンジラーメン',
 '쫄깃한 면발과 화끈한 국물',
 'Chewy noodles with fiery broth',
 '劲道面条配火辣汤底',
 'モチモチ麺と辛いスープ',
 4, 4, 'bag', 'soup', 'stovetop', 1000),

-- ───────────────────────────────────────────────
-- 삼양 봉지라면
-- ───────────────────────────────────────────────
(25, '불닭볶음면', 'Buldak Bokkeummyeon', '火鸡面', 'ブルダック炒め麺',
 'SNS 챌린지로 전 세계에 알려진 초극매운 닭볶음 소스 볶음면',
 'Super spicy stir-fried chicken sauce noodles famous worldwide through SNS challenges',
 '通过社交媒体挑战在全球闻名的超辣鸡肉酱炒面',
 'SNSチャレンジで世界中に知られた超激辛チキンソース炒め麺',
 '스리라차의 3~4배 수준의 매운맛',
 '3-4x spicier than Sriracha sauce',
 '辣度是辣椒酱的3-4倍',
 'スリラチャの3〜4倍の辛さ',
 '전 세계 60개국 이상 수출, 한국 라면 수출 1위',
 'Exported to 60+ countries, Korea''s #1 ramen export',
 '出口60多个国家，韩国拉面出口第一',
 '60カ国以上に輸出、韓国ラーメン輸出No.1',
 '쫄깃한 면에 달콤하고 매운 닭볶음 소스',
 'Chewy noodles with sweet and spicy stir-fried chicken sauce',
 '劲道面条配甜辣鸡肉酱',
 'モチモチ麺に甘辛チキンソース',
 4, 5, 'bag', 'dry', 'stovetop', 1400),

(26, '까르보 불닭볶음면', 'Carbo Buldak', '卡邦尼火鸡面', 'カルボブルダック',
 '불닭 소스에 크리미한 까르보나라 소스가 더해진 순한 버전',
 'Milder version with creamy carbonara sauce added to buldak sauce',
 '在火鸡面酱基础上加入奶油培根酱的温和版本',
 'クリーミーなカルボナーラソースを加えたマイルドなブルダック',
 '크리미한 파스타와 한국 매운 소스의 독특한 조합',
 'Unique combination of creamy pasta and Korean spicy sauce',
 '奶油意面与韩式辣酱的独特结合',
 'クリーミーなパスタと韓国辛いソースの独特な組み合わせ',
 '불닭 입문용으로 전 세계 외국인에게 가장 추천',
 'Most recommended for foreigners worldwide as buldak entry point',
 '作为火鸡面入门款，最受全球外国人推荐',
 '世界中の外国人へのブルダック入門として最もおすすめ',
 '크리미하고 쫄깃한 면발',
 'Creamy and chewy noodles',
 '奶香劲道的面条',
 'クリーミーでモチモチの麺',
 4, 3, 'bag', 'dry', 'stovetop', 1400),

(27, '핵불닭볶음면', 'Nuclear Buldak', '核弹火鸡面', '핵ブルダック',
 '불닭볶음면의 2배 매운맛, 극한의 스코빌 지수를 자랑하는 도전 라면',
 'Twice as spicy as original buldak, challenge ramen with extreme Scoville rating',
 '辣度是原版火鸡面的两倍，以极端斯高维尔辣度著称的挑战拉面',
 '元祖ブルダックの2倍の辛さ、極限のスコヴィル値を誇るチャレンジラーメン',
 '가장 매운 핫소스보다도 강렬한 수준의 매운맛',
 'Even more intense than the hottest hot sauces',
 '辣度甚至超过最辣的辣酱',
 '最も辛いホットソース以上の強烈な辛さ',
 '매운맛 도전 영상으로 유튜브에서 큰 인기',
 'Hugely popular on YouTube through spicy challenge videos',
 '以辣度挑战视频在YouTube上大受欢迎',
 '辛さチャレンジ動画でYouTubeで大人気',
 '쫄깃한 면에 극도로 매운 소스',
 'Chewy noodles with extremely spicy sauce',
 '劲道面条配极度辣味酱料',
 'モチモチ麺に極辛ソース',
 4, 5, 'bag', 'dry', 'stovetop', 1400),

(28, '로제 불닭볶음면', 'Rose Buldak', '玫瑰火鸡面', 'ロゼブルダック',
 '불닭 소스에 토마토 크림이 더해진 부드러운 로제 소스 볶음면',
 'Smooth rose sauce stir-fried noodles with tomato cream added to buldak sauce',
 '在火鸡面酱中加入番茄奶油的柔滑玫瑰酱炒面',
 'ブルダックソースにトマトクリームを加えた滑らかなロゼソース炒め麺',
 '아라비아타 파스타 소스와 한국 매운맛의 퓨전',
 'Fusion of arrabbiata pasta sauce and Korean spiciness',
 '阿拉比亚塔意面酱与韩式辣味的融合',
 'アラビアータソースと韓国の辛さのフュージョン',
 '크림 기반 음식을 좋아하는 서양 관광객에게 특히 인기',
 'Especially popular among Western tourists who enjoy cream-based dishes',
 '在喜爱奶油类食物的西方游客中特别受欢迎',
 'クリームベースの料理が好きな西洋人観光客に特に人気',
 '부드럽고 크리미한 면발',
 'Soft and creamy noodles',
 '柔软奶香的面条',
 '柔らかくクリーミーな麺',
 4, 3, 'bag', 'dry', 'stovetop', 1400),

-- ───────────────────────────────────────────────
-- 팔도 봉지라면
-- ───────────────────────────────────────────────
(29, '팔도비빔면', 'Paldo Bibimmyeon', '八道拌面', 'パルドビビム麺',
 '새콤달콤한 고추장 소스의 여름 대표 비빔면, 차갑게 먹는 것이 포인트',
 'Summer signature cold bibim noodles with sweet and tangy gochujang sauce, best served cold',
 '酸甜辣椒酱的夏季代表拌面，冷食为佳',
 '甘酸っぱいコチュジャンソースの夏の定番ビビム麺、冷やして食べるのがポイント',
 '달콤하고 매콤한 한국식 콜드 누들, 태국 냉국수와 비슷한 느낌',
 'Sweet and spicy Korean cold noodles, similar feel to Thai cold noodles',
 '甜辣韩式凉面，类似泰式凉面的感觉',
 '甘辛い韓国式冷麺、タイの冷たい麺に似た感じ',
 '여름 시즌 편의점 비빔면 판매 1위, 한국 여름 필수템',
 'Summer season convenience store bibim noodle #1 seller, Korean summer essential',
 '夏季便利店拌面销量第一，韩国夏季必备',
 '夏シーズンのコンビニビビム麺販売No.1、韓国の夏の必須アイテム',
 '얇고 쫄깃한 면발, 소스가 잘 배임',
 'Thin and chewy noodles that absorb sauce well',
 '细腻劲道的面条，充分吸收酱汁',
 '細くてモチモチの麺、ソースがよく染み込む',
 3, 2, 'bag', 'dry', 'stovetop', 1500),

(30, '틈새라면 빨계떡', 'Teumsae Ramen', '틈새拉面红年糕', 'テウムセラーメン',
 '서울 유명 분식집 틈새라면 맛을 재현한 극매운 빨간 국물, 떡볶이 스타일',
 'Extremely spicy red broth recreating the famous Teumsae restaurant taste with tteokbokki style',
 '重现首尔著名小吃店틈새拉面口味的极辣红色汤底，辣炒年糕风格',
 'ソウルの有名店のテウムセラーメンの味を再現した激辛赤スープ、トッポッキスタイル',
 '한국 떡볶이 국물과 매운 라면을 합친 강렬한 맛',
 'Intense flavor combining Korean tteokbokki broth and spicy ramen',
 '融合韩式辣炒年糕汤底与辣拉面的强烈口味',
 '韓国のトッポッキの出汁と辛いラーメンを組み合わせた強烈な味',
 '매운 한국 음식 마니아 외국인 관광객에게 인기',
 'Popular among foreign tourists who are fans of spicy Korean food',
 '受喜爱辣韩餐的外国游客欢迎',
 '辛い韓国料理ファンの外国人観光客に人気',
 '쫄깃한 면과 진한 매운 국물',
 'Chewy noodles with rich spicy broth',
 '劲道面条配浓郁辣味汤底',
 'モチモチ麺と濃い辛いスープ',
 4, 5, 'bag', 'soup', 'stovetop', 1500);
