-- 편의점 디저트/간식 가이드용 snack_items 테이블 생성 (Supabase SQL 에디터에서 실행)
-- gimbap_items/dosirak_items와 동일한 패턴: 다국어 텍스트 + 큐레이션 필드
-- 가격(price_krw)은 실제 조사 전 플레이스홀더(0)로 채워둠 — admin에서 실제 값으로 수정 필요

create table snack_items (
  id bigint generated always as identity primary key,
  order_num int not null default 0,
  name_ko text not null,
  name_en text,
  name_zh text,
  name_ja text,
  image_url text,
  flavor_desc_ko text,
  flavor_desc_en text,
  flavor_desc_zh text,
  flavor_desc_ja text,
  why_popular_ko text,
  why_popular_en text,
  why_popular_zh text,
  why_popular_ja text,
  allergen_note_ko text,
  allergen_note_en text,
  allergen_note_zh text,
  allergen_note_ja text,
  category text, -- 'drink' | 'ice_cream' | 'snack' | 'bread'
  price_krw int,
  manufacturer_url text
);

-- 한국인이 꼭 먹어보라고 추천하는 편의점 디저트/간식 대표 6종
-- (일반적으로 널리 알려진 정보 기준, 상품별 상세는 추후 admin에서 조사 후 입력)
insert into snack_items (order_num, name_ko, name_en, name_zh, name_ja, flavor_desc_ko, flavor_desc_en, flavor_desc_zh, flavor_desc_ja, why_popular_ko, why_popular_en, why_popular_zh, why_popular_ja, allergen_note_ko, allergen_note_en, allergen_note_zh, allergen_note_ja, category, price_krw) values
(1, '바나나맛우유', 'Banana Milk', '香蕉牛奶', 'バナナ牛乳',
 '달콤한 바나나 향 우유. 항아리 모양 용기가 특징.',
 'Sweet banana-flavored milk in a distinctive jar-shaped container.',
 '香甜的香蕉味牛奶，特色是坛子形状的容器。',
 '甘い バナナ風味の牛乳。壺型の容器が特徴。',
 '1974년 출시 이후 한국인의 국민 우유로 불리는 스테디셀러. 편의점 냉장고에서 항아리 모양 때문에 바로 찾을 수 있음.',
 'A steady bestseller since 1974, often called Korea''s "national milk." Easy to spot in the fridge thanks to its jar shape.',
 '自1974年上市以来被称为韩国国民牛奶的长销商品。因坛子造型很容易在冰柜中找到。',
 '1974年発売以来、韓国の"国民牛乳"と呼ばれるロングセラー。壺型なので冷蔵庫の中でもすぐ見つかる。',
 '우유(유당불내증 주의), 대두 함유.',
 'Contains milk (lactose caution) and soybean.',
 '含有牛奶（乳糖不耐受者注意）、大豆成分。',
 '牛乳（乳糖不耐症の方は注意）・大豆を含みます。',
 'drink', 0),
(2, '메로나', 'Melona', '哈密瓜冰棒', 'メロナ',
 '멜론 맛 아이스크림바. 부드럽고 크리미한 식감.',
 'Melon-flavored ice cream bar with a soft, creamy texture.',
 '哈密瓜味雪糕，口感柔软绵密。',
 'メロン味のアイスバー。柔らかくクリーミーな食感。',
 '1992년 출시된 한국 대표 아이스크림. 실제 멜론이 안 들어가도 향이 진해서 외국인들 사이에서도 SNS 인증 아이템으로 유명.',
 'A classic Korean ice cream since 1992. Contains no real melon but has a strong flavor — a popular social media item among foreign visitors.',
 '1992年上市的韩国代表性冰淇淋。虽不含真实哈密瓜，但香气浓郁，也是外国游客热衷打卡分享的人气单品。',
 '1992年発売の韓国を代表するアイス。実際のメロンは入っていないが香りが濃厚で、外国人の間でもSNS映えアイテムとして有名。',
 '우유 함유.',
 'Contains milk.',
 '含有牛奶成分。',
 '牛乳を含みます。',
 'ice_cream', 0),
(3, '허니버터칩', 'Honey Butter Chip', '蜂蜜黄油薯片', 'ハニーバターチップ',
 '달콤한 꿀과 버터 향이 나는 감자칩. 짠맛 위주의 기존 과자와 다른 단맛 중심.',
 'Potato chips with a sweet honey-butter flavor — unusually sweet compared to typical salty snacks.',
 '带有甜蜜蜂蜜黄油香气的薯片，与传统咸味零食不同，以甜味为主。',
 '甘い蜂蜜とバターの香りがするポテトチップス。塩味中心の従来のお菓子とは違う甘さが特徴。',
 '2014년 출시 당시 품절 대란을 일으켰던 화제의 과자. 지금도 편의점 인기 과자 상위권.',
 'Caused a nationwide shortage when it launched in 2014. Still one of the most popular snacks in convenience stores today.',
 '2014年上市时曾引发抢购断货热潮的话题零食，至今仍是便利店的人气零食之一。',
 '2014年の発売当時、品切れが続出するほど話題になったお菓子。今でもコンビニの人気スナック上位。',
 '밀가루, 우유 함유.',
 'Contains wheat and milk.',
 '含有小麦、牛奶成分。',
 '小麦・牛乳を含みます。',
 'snack', 0),
(4, '옥동자(젤리)', 'Ok-dongja Jelly', '玉童子软糖', 'オクドンジャ（グミ）',
 '옥수수수염차 맛 소프트 젤리. 새콤달콤한 맛과 쫄깃한 식감.',
 'Soft jelly with a corn-silk tea flavor. Sweet and tangy with a chewy texture.',
 '玉米须茶味软糖，酸甜口味，口感Q弹。',
 'とうもろこし茶風味のソフトグミ。甘酸っぱい味とモチモチ食感。',
 '독특한 모양과 이름으로 SNS에서 화제가 된 젤리. 편의점 간식 코너의 대표적인 재미 아이템.',
 'Known for its quirky shape and name, this jelly became a social media talking point — a fun standout in the snack aisle.',
 '因造型独特、名字有趣而在社交媒体上引发话题的软糖，是便利店零食区颇具趣味性的代表商品。',
 'ユニークな形と名前でSNSで話題になったグミ。コンビニのお菓子コーナーの代表的な話題アイテム。',
 '젤라틴(돼지 유래 가능) 함유. 채식·할랄 기준은 상품마다 다르므로 라벨 확인 필요.',
 'Contains gelatin (may be pork-derived). Vegetarian/halal suitability varies by product — check the label.',
 '含有明胶（可能来源于猪）成分。是否适合素食、清真因产品而异，请确认标签。',
 'ゼラチン（豚由来の可能性あり）を含みます。ベジタリアン・ハラール対応は商品により異なるためラベルをご確認ください。',
 'snack', 0),
(5, '초코송이', 'Chocosong-i', '巧克力松茸饼干', 'チョコソンイ',
 '버섯 모양 과자에 초콜릿을 입힌 스낵. 바삭한 과자와 달콤한 초콜릿의 조합.',
 'Mushroom-shaped cookies coated in chocolate. A combination of crunchy cookie and sweet chocolate.',
 '蘑菇造型饼干裹上巧克力的零食，酥脆饼干与甜巧克力的组合。',
 'きのこ型のクッキーにチョコレートをコーティングしたお菓子。サクサクのクッキーと甘いチョコの組み合わせ。',
 '1984년 출시된 스테디셀러 과자. 독특한 버섯 모양 때문에 처음 보는 외국인들이 신기해하는 아이템.',
 'A steady seller since 1984. The unusual mushroom shape often surprises first-time foreign visitors.',
 '1984年上市的长销零食。独特的蘑菇造型让初次见到的外国游客感到新奇。',
 '1984年発売のロングセラー菓子。ユニークなきのこの形が、初めて見る外国人には珍しく映るアイテム。',
 '밀가루, 우유, 대두 함유.',
 'Contains wheat, milk, and soybean.',
 '含有小麦、牛奶、大豆成分。',
 '小麦・牛乳・大豆を含みます。',
 'snack', 0),
(6, '소보로빵', 'Soboro Bread', '酥皮面包', 'そぼろパン',
 '겉면에 바삭한 크럼블(소보로)을 얹은 빵. 달콤하고 겉은 바삭, 속은 부드러움.',
 'Bread topped with a crunchy crumble (soboro). Sweet, crispy outside, soft inside.',
 '表面覆盖酥脆碎屑（酥波罗）的面包，甜味十足，外酥内软。',
 '表面にサクサクのクランブル（そぼろ）をのせたパン。甘くて外はサクサク、中はふんわり。',
 '한국 빵집·편의점의 스테디셀러 빵. 저렴한 가격에 든든해서 아침 대용이나 간식으로 많이 찾음.',
 'A steady bestseller at bakeries and convenience stores alike. Affordable and filling — popular as a breakfast substitute or snack.',
 '韩国面包店和便利店的长销面包。价格实惠又饱腹，常被当作早餐替代品或零食。',
 '韓国のパン屋・コンビニのロングセラーパン。手頃な価格で満足感があり、朝食代わりやおやつとしてよく選ばれる。',
 '밀가루, 계란, 우유 함유.',
 'Contains wheat, egg, and milk.',
 '含有小麦、鸡蛋、牛奶成分。',
 '小麦・卵・牛乳を含みます。',
 'bread', 0);
